# Adapted from:
# https://github.com/swaggest/rest/blob/b19db8242abe420b23ea8ece43dd2fb79056a943/.github/workflows/bench.yml
name: bench

on:
  push:
    branches: [main] # on pushes TO main
  pull_request:
    branches: [main] # on pull requests AGAINST main

# cancel CI runs when a new commit is pushed to any branch except main
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  BENCH_RUNS: 10

jobs:
  baseline:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - uses: actions/checkout@v4

      - name: cache previous baseline results
        uses: actions/cache@v4
        with:
          path: |
            bench-*.txt
          key: ${{ runner.os }}-bench-results-${{ hashFiles('websocket_benchmark_test.go') }}
          restore-keys: |
            ${{ runner.os }}-bench-results-

      - name: run benchmarks
        run: |
          COMMIT="${GITHUB_SHA::7}"
          COMMIT_URL="https://github.com/mccutchen/websocket/commit/$COMMIT"
          COMMIT_LINK="[$COMMIT]($COMMIT_URL)"

          echo -n "$COMMIT" > bench-commit-main.txt
          make bench | tee bench-results-main.txt

          cat <<EOF >>$GITHUB_STEP_SUMMARY
          ### benchmark results @ $COMMIT_LINK
          \`\`\`
          $(cat bench-results-main.txt)
          \`\`\`
          EOF
