name: test

on:
  push:
    branches: [main] # on pushes TO main
  pull_request:
    branches: [main] # on pull requests AGAINST main

# cancel CI runs when a new commit is pushed to any branch except main
concurrency:
  group: "test-${{ github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

env:
  OUT_DIR:    "out"
  REPORT_DIR: "out/autobahn" # ideally this would reference $OUT_DIR but GH Actions doesn't support that

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build against the two latest releases, to match golang's release
        # policy: https://go.dev/doc/devel/release#policy
        go-version:
        - 'stable'
        - 'oldstable'

    steps:
    - name: setup
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go-version}}

    - name: checkout
      uses: actions/checkout@v4

    - name: test
      run: make testci

    - name: report code coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
      if: ${{ matrix.go-version == 'stable' }}

  autobahn:
    runs-on: ubuntu-latest

    steps:
    - name: setup
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: checkout
      uses: actions/checkout@v4

    - name: run autobahn tests
      run: |
        # this will write the report to $REPORT_DIR
        make testautobahn

        # claen up unneded structured json report data from autobahn before
        # uploading the artifact
        find "${OUT_DIR}" -type f -name '*.json' -delete

    - name: upload autobahn report artifact
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main'
      with:
        name: autobahn-report
        path: ${{ env.REPORT_DIR }}/report
        retention-days: 1

  publish-github-pages:
    runs-on: ubuntu-latest
    needs: autobahn
    if: github.ref == 'refs/heads/main'

    # Set permissions needed for GitHub Pages deployment
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for commit timestamps

    - name: setup pages
      uses: actions/configure-pages@v4

    - name: download latest autobahn report
      uses: actions/download-artifact@v4
      with:
        name: autobahn-report
        path: "${{ env.OUT_DIR }}/latest-report"

    - name: build github pages
      run: ./ci/build-github-pages

    - name: upload github pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "${{ env.OUT_DIR }}/reports"

    - name: deploy github pages
      id: deployment
      uses: actions/deploy-pages@v4

  examples:
    runs-on: ubuntu-latest

    steps:
    - name: setup
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: checkout
      uses: actions/checkout@v4

    - name: build examples
      run: make examples
